import esbuild from 'esbuild'
import process from 'process'
import fs from 'fs'
import { createRequire } from 'module'
import builtins from 'builtin-modules'
import esbuildSvelte from 'esbuild-svelte'
import sveltePreprocess from 'svelte-preprocess'

const require = createRequire(import.meta.url)

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

// pdf.js worker 内联：Obsidian 禁用了 Chromium 内置 PDF viewer 且无 service worker，
// pdfjs-dist 的 worker 文件必须随产物打包 —— 将 pdf.worker.min.mjs 以字符串注入
// Blob URL（单文件产物，保持三件套 + cmp 校验流程不变；规避 ?url 拷文件方案）
const pdfWorkerInline = {
    name: 'pdf-worker-inline',
    setup(build) {
        build.onResolve({ filter: /^pdfjs-dist\/build\/pdf\.worker\.min\.mjs$/ }, (args) => {
            return { path: args.path, namespace: 'pdf-worker' };
        });
        build.onLoad({ filter: /.*/, namespace: 'pdf-worker' }, () => {
            const workerPath = require.resolve('pdfjs-dist/build/pdf.worker.min.mjs');
            const code = fs.readFileSync(workerPath, 'utf8');
            const injected = `const _workerCode = ${JSON.stringify(code)};\n` +
                `export default URL.createObjectURL(new Blob([_workerCode], { type: 'text/javascript' }));`;
            return { contents: injected, loader: 'js' };
        });
    },
}

const prod = process.argv[2] === 'production'

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ['main.ts'],
    bundle: true,
    plugins: [
        pdfWorkerInline,
        esbuildSvelte({
            compilerOptions: { css: 'injected' },
            preprocess: sveltePreprocess(),
            onwarn: (warning, handler) => {
                // 忽略 a11y 告警（Obsidian 插件表单控件，非公开网页；label 关联后续完善）
                if (warning.code && String(warning.code).startsWith('a11y-')) return;
                handler(warning);
            },
        }),
    ],
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...builtins,
    ],
    format: 'cjs',
    target: 'es2018',
    logLevel: 'info',
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outfile: 'main.js',
})

if (prod) {
    await context.rebuild()
    process.exit(0)
} else {
    await context.watch()
}
